services:
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - db-prod
    restart: on-failure
    profiles:
      - prod

  db-prod:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    profiles:
      - prod
  
  # dev environment with live-reload
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    depends_on:
      - db-dev
    profiles:
      - dev

  db-dev:
    image: postgres:17
    env_file:
      - .env.dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - dev

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      - db-test
    profiles:
      - test

  db-test:
    image: postgres:17
    env_file:
      - .env.test
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    profiles:
      - test

volumes:
  pgdata_prod:
  pgdata_dev:
  pgdata_test:

